### ISSUE TITLE
Can't use Function.prototype.bind on phantomjs 1.9

### ISSUE THREAD

**Issue by danconnell** [prerender/prerender#273]
Hi,

I'm running prerender on Heroku (with a 2X dyno so 1GB of RAM) and using it for an Ember app. If a page is loaded a few times in quick succession, prerender fails to render my app properly on the third or fourth time. (Running the latest code from your repo v3.22.5.)

The issue seems to be coming from this:
`phantom stdout: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)') `

This error happens everytime even when it's working, but then other errors pop up and the Ember app doesn't render at all. Is it maybe because this error is happening everytime that it eventually fails altogether?

Not really sure what to do to investigate this further or resolve the issue. Any help is appreciated. Thanks!

**Comment by danconnell** [comment]
Edited original post to properly reflect what's happening after investigating a bit more.

**Comment by danconnell** [comment]
Discovered from http://stackoverflow.com/a/34160714 that I need phantomjs 2.

I tried to use the phantomjs branch https://github.com/prerender/prerender/pull/266 from this repo but had to fork it and set it to create the phantom with --web-security=no to get around https://github.com/amir20/phantomjs-node/issues/345 and set its phantomjs to a fork of thoop's phantomjs fork and set phantomjs to 2.1.1 so it could download an available file from https://bitbucket.org/ariya/phantomjs/downloads/.

Overall, not a fun little hack, but it seems to work.

Feel free to close this issue, or close it once you're supporting phantomjs 2, since other people might have this problem where they can't prerender JS with `Function.prototype.bind` in it.

**Comment by thoop** [comment]
We actually have a shim that should load bind if it's not available, so it should be working in 1.9.8.

https://github.com/prerender/prerender/blob/master/lib/injections/bind.js

--web-security=no isn't great to run with security-wise, which is why we haven't upgraded to 2.1 yet.

**Comment by danconnell** [comment]
Any idea why I was getting that error then on the latest prerender if the shim should handle it?

Also, out of curiousity, what does --web-security=no expose me to exactly? Is it something I should be concerned about?

**Comment by thoop** [comment]
web-security=no allows all requests to other domains and disables CORS. Since you are loading only pages on your website, that shouldn't be an issue, but it could be a possible attack vector.

You didn't have the disable injections flag set, did you? Otherwise, the bind shim should be loaded every time.

**Comment by danconnell** [comment]
Thanks, good to know.

And nope, I don't have that flag set. Odd that it doesn't appear to be working for me. 

I'm not too familiar with how prerender works, so I may be way off but the only thing I can think of is that the code that's erroring out isn't code that I include myself. I put a single line of Javascript to call Segment (https://segment.com/), which then has a Zendesk integration enabled. So it's technically getting added to the page later by Segment. Could that be it?

**Comment by thoop** [comment]
Hmm, I don't think so. Any javascript should execute just fine and if that injection was happening then bind would work too.

**Comment by danconnell** [comment]
Weird then. I'll stick with my workaround for now, and once the issue with phantomjs 2 gets worked out and you're able to use it, I'll try switching back.

**Comment by thoop** [comment]
I just merged a new change into master to support PhantomJS 2.1 so this issue shouldn't be a problem any more. Feel free to reopen if you try it out and run into prototype.bind issues!

**Comment by danconnell** [comment]
Working much better now. Thanks, @thoop.

I'm happy the restart-heroku hack is gone too. Nice work.

**Comment by thoop** [comment]
Yeah that restart shouldn't be needed anymore since we restart phantomjs after a certain number of iterations but let me know if you end up running into anything.
